//! Rust source generation from the IDL AST. Normative reference:
//! ADR-0007.
//!
//! Output is deterministic and emitted in canonical rustfmt layout;
//! the generated module is additionally exempt via rustfmt::skip in
//! nbe-dom's lib.rs.

use crate::idl::{Interface, Member};

/// Convert an IDL lowerCamelCase identifier to Rust snake_case.
/// Every ASCII uppercase character after position 0 becomes an
/// underscore followed by the lowercase letter. Acronym-containing
/// names are split per letter; our IDL avoids acronyms.
#[must_use]
pub fn to_snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// Generate the complete Rust source for the parsed interfaces.
#[must_use]
pub fn generate_interfaces(interfaces: &[Interface]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by nbe-bindings IDL codegen from idl/dom.webidl.\n");
    out.push_str("//! DO NOT EDIT BY HAND: regenerate with\n");
    out.push_str("//! `NBE_UPDATE_GOLDENS=1 cargo test -p nbe-bindings`.\n\n");
    for (index, interface) in interfaces.iter().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        generate_interface(&mut out, interface);
    }
    out
}

fn generate_interface(out: &mut String, interface: &Interface) {
    match &interface.parent {
        Some(parent) => {
            out.push_str(&format!(
                "/// IDL interface `{}`, inherits `{}`.\n",
                interface.name, parent
            ));
            out.push_str(&format!("pub trait {}: {} {{\n", interface.name, parent));
        }
        None => {
            out.push_str(&format!("/// IDL interface `{}`.\n", interface.name));
            out.push_str(&format!("pub trait {} {{\n", interface.name));
        }
    }
    for (index, member) in interface.members.iter().enumerate() {
        if index > 0 {
            out.push('\n');
        }
        generate_member(out, member);
    }
    out.push_str("}\n");
}

fn generate_member(out: &mut String, member: &Member) {
    match member {
        Member::Attribute { ty, name, readonly } => {
            let getter = to_snake_case(name);
            let qualifier = if *readonly { " (readonly)" } else { "" };
            out.push_str(&format!("    /// IDL attribute `{}`{}.\n", name, qualifier));
            out.push_str(&format!(
                "    fn {}(&self) -> {};\n",
                getter,
                ty.rust_value_type()
            ));
            if !*readonly {
                out.push_str(&format!("    /// Setter for IDL attribute `{}`.\n", name));
                out.push_str(&format!(
                    "    fn set_{}(&mut self, value: {});\n",
                    getter,
                    ty.rust_param_type()
                ));
            }
        }
        Member::Method { ret, name, args } => {
            out.push_str(&format!("    /// IDL method `{}`.\n", name));
            let mut parameters = String::new();
            for (index, arg) in args.iter().enumerate() {
                if index > 0 {
                    parameters.push_str(", ");
                }
                parameters.push_str(&format!(
                    "{}: {}",
                    to_snake_case(&arg.name),
                    arg.ty.rust_param_type()
                ));
            }
            let return_type = match ret {
                Some(ty) => format!(" -> {}", ty.rust_value_type()),
                None => String::new(),
            };
            let self_part = if parameters.is_empty() {
                "&self".to_string()
            } else {
                format!("&self, {parameters}")
            };
            out.push_str(&format!(
                "    fn {}({}){};\n",
                to_snake_case(name),
                self_part,
                return_type
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::idl::{IdlType, Member};

    #[test]
    fn snake_case_naming() {
        assert_eq!(to_snake_case("nodeType"), "node_type");
        assert_eq!(to_snake_case("hasChildNodes"), "has_child_nodes");
        assert_eq!(to_snake_case("simple"), "simple");
    }

    #[test]
    fn generated_traits_have_expected_shape() {
        let interfaces = vec![Interface {
            name: "Node".into(),
            parent: None,
            members: vec![Member::Attribute {
                ty: IdlType::UnsignedLong,
                name: "nodeType".into(),
                readonly: true,
            }],
        }];
        let source = generate_interfaces(&interfaces);
        assert!(source.contains("pub trait Node {"));
        assert!(source.contains("fn node_type(&self) -> u32;"));
        assert!(!source.contains("set_node_type"));
    }
}
