//! Generated by nbe-bindings IDL codegen from idl/dom.webidl.
//! DO NOT EDIT BY HAND: regenerate with
//! `NBE_UPDATE_GOLDENS=1 cargo test -p nbe-bindings`.

/// IDL interface `Node`.
pub trait Node {
    /// IDL attribute `nodeType` (readonly).
    fn node_type(&self) -> u32;

    /// IDL attribute `nodeName`.
    fn node_name(&self) -> String;
    /// Setter for IDL attribute `nodeName`.
    fn set_node_name(&mut self, value: &str);
}

/// IDL interface `Element`, inherits `Node`.
pub trait Element: Node {
    /// IDL attribute `tagName`.
    fn tag_name(&self) -> String;
    /// Setter for IDL attribute `tagName`.
    fn set_tag_name(&mut self, value: &str);
}

/// IDL interface `CodegenProbe`.
pub trait CodegenProbe {
    /// IDL method `poke`.
    fn poke(&self, count: u32);

    /// IDL method `check`.
    fn check(&self, name: &str, delta: i32, ratio: f64) -> bool;
}
